### ISSUE TITLE
Cant use screens menu

### ISSUE THREAD

**Issue by CortexQc** [DrJamgo/SoulJuice-public#1]
**Describe the bug**
Just started the game,
The android home menu stay on screen.
Clicking on all the screen dont open or change nothing
I can only use android home menu on bottom of the screen.
 Samsung S10 android 11

![Screenshot_20210226-083437](https://user-images.githubusercontent.com/79704755/109307442-a949e680-780e-11eb-829d-675842af739a.jpg)

**To Reproduce**
2. Scroll down to '....'
3. See error.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DrJamgo** [comment]
Thanks for the bug report. Just to understand clearly: you are unable to click any of the icons?

**Comment by CortexQc** [comment]
Exactly no interaction with the game. And the android menu stay here.

**Comment by DrJamgo** [comment]
Resolved in v0.6.3

**Comment by CortexQc** [comment]
working ! thx
