### ISSUE TITLE
Icon naming

### ISSUE THREAD

**Issue by CortexQc** [DrJamgo/SoulJuice-public#2]
**Describe the bug**
Icon name letter error

**Screenshots**
![Screenshot_20210226-120335_One UI Home](https://user-images.githubusercontent.com/79704755/109331614-0d7aa380-782b-11eb-8fa5-2fc233ce029a.jpg)

**Comment by DrJamgo** [comment]
:-/

**Comment by DrJamgo** [comment]
fixed in 0.3.1
