### ISSUE TITLE
progress stops after first "wave"

### ISSUE THREAD

**Issue by SodTiwaz** [DrJamgo/SoulJuice-public#3]
**Describe the bug**
Game doesn't progress

**To Reproduce**
1. Play the game to the "end" of the path
2. Game is stuck with a time that doesn't advance

**Expected behavior**
Menus at the bottom of the screen may resolve this but those don't work either so I'm unsure if they're the same issue.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: LG V60
 - OS: Android
 - Browser n/a downloaded from app store
 - Version 10

**Additional context**

**Comment by DrJamgo** [comment]
Congratulation.. you finished the first level (the only level in v0.2.0)

In future the displayed time will be submitted to the leader board.

For now it kust stays there forever starring back at you.

**Comment by DrJamgo** [comment]
The progress is now in percentage..
