### ISSUE TITLE
Vertical line brightness mismatch 

### ISSUE THREAD

**Issue by Niutels** [DrJamgo/SoulJuice-public#4]
**Describe the bug**
Vertical line on the right side of the screen when the phone's screen is horizontal.

**Screenshots**
![1614379727196](https://user-images.githubusercontent.com/26779218/109363769-f51e7f00-7852-11eb-9d4f-545e4013a147.jpg)

**Smartphone (please complete the following information):**
 - Device: Redmi Note 6 Pro

**Comment by DrJamgo** [comment]
fixed in 0.3.1
