### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zyzh94** [DrJamgo/SoulJuice-public#5]
Could start the game for the first time. Could not click on anything. Restarted the game. And the only gets errors

**Comment by zyzh94** [comment]
![Screenshot_20210310-081146](https://user-images.githubusercontent.com/80382832/110590629-52ca9980-8178-11eb-9588-2b0d4d58c827.jpg)

**Comment by DrJamgo** [comment]
Saving resolved in v0.6.1
