### ISSUE TITLE
No in game icon

### ISSUE THREAD

**Issue by Darfool** [DrJamgo/SoulJuice-public#6]
**Describe the bug**
I think the screenshot is enough description.

**To Reproduce**

**Expected behavior**
Having icons!

**Screenshots**
![Screenshot_20210328-174443](https://user-images.githubusercontent.com/36534235/112758212-5a4dc780-8fed-11eb-9106-262708cd77f6.png)

**Smartphone (please complete the following information):**
 - Device: Doogee s95pro
 - OS: [android 9]
 

**Additional context**
Hope you'll find what this bug is about!

**Comment by DrJamgo** [comment]
Hi there.. I think the icons image is just bigger then it is is supported on some devices. I will have to split it up into smaller pieces.

Thabks for submitting the issue.

**Comment by DrJamgo** [comment]
Resolved in v0.6.4
